name: malison
version: 0.13.0
description: A little terminal UI package for the browser.
homepage: https://github.com/munificent/malison
dependencies:
  piecemeal: 
    path: ../piecemeal
dev_dependencies:
  build_runner: any
  build_web_compilers: any
environment:
  sdk: ">=2.12.0 <3.0.0"